### ISSUE TITLE
[Feature request]: Make USER_ID_CLAIM configurable

### ISSUE THREAD

**Issue by tongpu** [SchweizerischeBundesbahnen/netzgrafik-editor-backend#3]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-backend/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-backend/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Request type

Request for enhancement of a component

### Functionality

Currently the `USER_ID_CLAIM` in [AuthenticationService.java](https://github.com/SchweizerischeBundesbahnen/netzgrafik-editor-backend/blob/54970a1d272be6942e951e94f1ca5c1f510ceaf9/src/main/java/ch/sbb/pfi/netzgrafikeditor/api/common/AuthenticationService.java#L35) is hard coded to `sub`, but as not every OIDC integration will be the same we should make this configurable.

**Comment by aiAdrian** [comment]
Wan't resolve - outdated
